Repository vaco-breaker/sorting-algorithm-visualization, pull requests merged in 2024-09, with the labels that each got.

#1 feat: selection sorting 완료
  assets/styles/style.css
  javascript/index.js
  javascript/sort/selection.js
Labels: enhancement

#7 feat: bubble sorting 완료
  javascript/index.js
  javascript/sort/bubble.js
Labels: enhancement

#6 feat: insertion sorting 완료
  assets/styles/style.css
  javascript/index.js
  javascript/sort/insertion.js
Labels: enhancement

#18 feat: sorting input 최대값 기준 막대 그래프 크기 구현
  assets/styles/style.css
  javascript/index.js
Labels: enhancement

#19 feat: 애니메이션 동작시, input, button disabled 되게 하기
  assets/styles/style.css
  javascript/index.js
Labels: enhancement

#21 fix: submit 버튼 눌리게 수정
  javascript/index.js
Labels: bug

#22 feat: submit 시 최초 그래프 렌더링에 대한 fadeIn animation 적용
  assets/styles/style.css
  javascript/index.js
Labels: enhancement

#23 feat: 병합 정렬 알고리즘 애니메이션 구현 완료
  javascript/index.js
  javascript/sort/merge.js
Labels: enhancement

#24 feat: 각 정렬에 대한 fixed와 sorting effect 구현 완료
  .prettierrc
  assets/styles/style.css
  javascript/index.js
  javascript/sort/bubble.js
  javascript/sort/insertion.js
  javascript/sort/merge.js
  javascript/sort/selection.js
Labels: enhancement

#26 feat: 높낮이 변화에 따른 애니메이션 추가(requireAnimationFrame; a.k.a. rAF)
  assets/styles/style.css
  javascript/index.js
  javascript/sort/merge.js
Labels: enhancement

#27 docs: Revise readme
  README.md
  assets/images/rAF.png
Labels: documentation

#28 docs: README.md 수정(2)
  README.md
Labels: documentation
